# Generated by Django 3.2.6 on 2021-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210901_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('userIMG', models.ImageField(upload_to='media')),
                ('userphone', models.ImageField(max_length=127, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='cards',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Card',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
