# Generated by Django 3.2.6 on 2021-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210908_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='userphone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
