# Generated by Django 3.2.6 on 2021-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_userdet_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='userphone',
            field=models.IntegerField(null=True),
        ),
    ]
