# Generated by Django 3.2.6 on 2021-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210913_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='Details',
            field=models.TextField(),
        ),
    ]
